name: Pyphen
description: Hyphenation in pure Python
license: LGPL / GPL / MPL
public: true
url: http://www.pyphen.org/
pystil: https://kozea.pystil.org/pystil.js

footer:
  - A Kozea Project:
      link: http://community.kozea.fr/
  - Optimized for Standards:
      link: http://validator.w3.org/check?uri=referer

project (git):
  url: git://github.com/Kozea/Pyphen.git
  path: pyphen

code browser (github):
  project name: Kozea/Pyphen
  ribbon: Fork me on GitHub

bug tracker (github):
  project name: Kozea/Pyphen

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: Pyphen
